[2021-05-25 21:21:56,250] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: covid19_cases_Jordan.Scoring_Report 2021-05-25T19:53:07.052122+00:00 [queued]>
[2021-05-25 21:21:56,490] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: covid19_cases_Jordan.Scoring_Report 2021-05-25T19:53:07.052122+00:00 [queued]>
[2021-05-25 21:21:56,492] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-05-25 21:21:56,492] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-05-25 21:21:56,502] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-05-25 21:21:56,702] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): Scoring_Report> on 2021-05-25T19:53:07.052122+00:00
[2021-05-25 21:21:56,864] {standard_task_runner.py:52} INFO - Started process 258 to run task
[2021-05-25 21:21:56,977] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'covid19_cases_Jordan', 'Scoring_Report', '2021-05-25T19:53:07.052122+00:00', '--job-id', '116', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/workflow.py', '--cfg-path', '/tmp/tmp2rya_9wi', '--error-file', '/tmp/tmpigoewi5z']
[2021-05-25 21:21:57,022] {standard_task_runner.py:77} INFO - Job 116: Subtask Scoring_Report
[2021-05-25 21:21:57,421] {logging_mixin.py:104} INFO - Running <TaskInstance: covid19_cases_Jordan.Scoring_Report 2021-05-25T19:53:07.052122+00:00 [running]> on host 4e0af5d83701
[2021-05-25 21:21:57,676] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=waed
AIRFLOW_CTX_DAG_ID=covid19_cases_Jordan
AIRFLOW_CTX_TASK_ID=Scoring_Report
AIRFLOW_CTX_EXECUTION_DATE=2021-05-25T19:53:07.052122+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-25T19:53:07.052122+00:00
[2021-05-25 21:21:59,115] {font_manager.py:1423} INFO - Generating new fontManager, this may take some time...
[2021-05-25 21:22:04,138] {font_manager.py:1068} WARNING - Matplotlib is building the font cache; this may take a moment.
[2021-05-25 21:22:20,236] {taskinstance.py:1455} ERROR - [Errno 13] Permission denied: '/opt/airflowJordan_scoring_report.csv'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/workflow.py", line 115, in scoringReport
    DF_Jordan_3.to_csv(AIRFLOW_HOME + 'Jordan_scoring_report.csv')
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 3170, in to_csv
    formatter.save()
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/formats/csvs.py", line 190, in save
    compression=dict(self.compression_args, method=self.compression),
  File "/home/airflow/.local/lib/python3.6/site-packages/pandas/io/common.py", line 493, in get_handle
    f = open(path_or_buf, mode, encoding=encoding, errors=errors, newline="")
PermissionError: [Errno 13] Permission denied: '/opt/airflowJordan_scoring_report.csv'
[2021-05-25 21:22:20,594] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=covid19_cases_Jordan, task_id=Scoring_Report, execution_date=20210525T195307, start_date=20210525T212156, end_date=20210525T212220
[2021-05-25 21:22:20,853] {local_task_job.py:146} INFO - Task exited with return code 1
